# DO NOT EDIT THIS FILE!
#
# Python module wordyGame generated by omniidl

import omniORB
omniORB.updateModule("wordyGame")

# ** 1. Stub files contributing to this module
import Wordy_idl

# ** 2. Sub-modules

# ** 3. End
