# Python stubs generated by omniidl from Wordy.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "wordyGame"
#
__name__ = "wordyGame"
_0_wordyGame = omniORB.openModule("wordyGame", r"Wordy.idl")
_0_wordyGame__POA = omniORB.openModule("wordyGame__POA", r"Wordy.idl")


# struct Player
_0_wordyGame.Player = omniORB.newEmptyClass()
class Player (omniORB.StructBase):
    _NP_RepositoryId = "IDL:wordyGame/Player:1.0"

    def __init__(self, username, password):
        self.username = username
        self.password = password

_0_wordyGame.Player = Player
_0_wordyGame._d_Player  = (omniORB.tcInternal.tv_struct, Player, Player._NP_RepositoryId, "Player", "username", (omniORB.tcInternal.tv_string,0), "password", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_Player = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_Player)
omniORB.registerType(Player._NP_RepositoryId, _0_wordyGame._d_Player, _0_wordyGame._tc_Player)
del Player

# struct Word
_0_wordyGame.Word = omniORB.newEmptyClass()
class Word (omniORB.StructBase):
    _NP_RepositoryId = "IDL:wordyGame/Word:1.0"

    def __init__(self, username, wordSub):
        self.username = username
        self.wordSub = wordSub

_0_wordyGame.Word = Word
_0_wordyGame._d_Word  = (omniORB.tcInternal.tv_struct, Word, Word._NP_RepositoryId, "Word", "username", (omniORB.tcInternal.tv_string,0), "wordSub", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_Word = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_Word)
omniORB.registerType(Word._NP_RepositoryId, _0_wordyGame._d_Word, _0_wordyGame._tc_Word)
del Word

# typedef ... StringSeq
class StringSeq:
    _NP_RepositoryId = "IDL:wordyGame/StringSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_wordyGame.StringSeq = StringSeq
_0_wordyGame._d_StringSeq  = (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0)
_0_wordyGame._ad_StringSeq = (omniORB.tcInternal.tv_alias, StringSeq._NP_RepositoryId, "StringSeq", (omniORB.tcInternal.tv_sequence, (omniORB.tcInternal.tv_string,0), 0))
_0_wordyGame._tc_StringSeq = omniORB.tcInternal.createTypeCode(_0_wordyGame._ad_StringSeq)
omniORB.registerType(StringSeq._NP_RepositoryId, _0_wordyGame._ad_StringSeq, _0_wordyGame._tc_StringSeq)
del StringSeq

# typedef ... CharSeq
class CharSeq:
    _NP_RepositoryId = "IDL:wordyGame/CharSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_wordyGame.CharSeq = CharSeq
_0_wordyGame._d_CharSeq  = (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_char, 0)
_0_wordyGame._ad_CharSeq = (omniORB.tcInternal.tv_alias, CharSeq._NP_RepositoryId, "CharSeq", (omniORB.tcInternal.tv_sequence, omniORB.tcInternal.tv_char, 0))
_0_wordyGame._tc_CharSeq = omniORB.tcInternal.createTypeCode(_0_wordyGame._ad_CharSeq)
omniORB.registerType(CharSeq._NP_RepositoryId, _0_wordyGame._ad_CharSeq, _0_wordyGame._tc_CharSeq)
del CharSeq

# typedef ... WordSeq
class WordSeq:
    _NP_RepositoryId = "IDL:wordyGame/WordSeq:1.0"
    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")
_0_wordyGame.WordSeq = WordSeq
_0_wordyGame._d_WordSeq  = (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordyGame/Word:1.0"], 0)
_0_wordyGame._ad_WordSeq = (omniORB.tcInternal.tv_alias, WordSeq._NP_RepositoryId, "WordSeq", (omniORB.tcInternal.tv_sequence, omniORB.typeMapping["IDL:wordyGame/Word:1.0"], 0))
_0_wordyGame._tc_WordSeq = omniORB.tcInternal.createTypeCode(_0_wordyGame._ad_WordSeq)
omniORB.registerType(WordSeq._NP_RepositoryId, _0_wordyGame._ad_WordSeq, _0_wordyGame._tc_WordSeq)
del WordSeq

# exception noOtherPlayersAvailable
_0_wordyGame.noOtherPlayersAvailable = omniORB.newEmptyClass()
class noOtherPlayersAvailable (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyGame/noOtherPlayersAvailable:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyGame.noOtherPlayersAvailable = noOtherPlayersAvailable
_0_wordyGame._d_noOtherPlayersAvailable  = (omniORB.tcInternal.tv_except, noOtherPlayersAvailable, noOtherPlayersAvailable._NP_RepositoryId, "noOtherPlayersAvailable", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_noOtherPlayersAvailable = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_noOtherPlayersAvailable)
omniORB.registerType(noOtherPlayersAvailable._NP_RepositoryId, _0_wordyGame._d_noOtherPlayersAvailable, _0_wordyGame._tc_noOtherPlayersAvailable)
del noOtherPlayersAvailable

# exception invalidWord
_0_wordyGame.invalidWord = omniORB.newEmptyClass()
class invalidWord (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyGame/invalidWord:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyGame.invalidWord = invalidWord
_0_wordyGame._d_invalidWord  = (omniORB.tcInternal.tv_except, invalidWord, invalidWord._NP_RepositoryId, "invalidWord", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_invalidWord = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_invalidWord)
omniORB.registerType(invalidWord._NP_RepositoryId, _0_wordyGame._d_invalidWord, _0_wordyGame._tc_invalidWord)
del invalidWord

# exception noSubmittedWord
_0_wordyGame.noSubmittedWord = omniORB.newEmptyClass()
class noSubmittedWord (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyGame/noSubmittedWord:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyGame.noSubmittedWord = noSubmittedWord
_0_wordyGame._d_noSubmittedWord  = (omniORB.tcInternal.tv_except, noSubmittedWord, noSubmittedWord._NP_RepositoryId, "noSubmittedWord", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_noSubmittedWord = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_noSubmittedWord)
omniORB.registerType(noSubmittedWord._NP_RepositoryId, _0_wordyGame._d_noSubmittedWord, _0_wordyGame._tc_noSubmittedWord)
del noSubmittedWord

# exception invalidLetters
_0_wordyGame.invalidLetters = omniORB.newEmptyClass()
class invalidLetters (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyGame/invalidLetters:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyGame.invalidLetters = invalidLetters
_0_wordyGame._d_invalidLetters  = (omniORB.tcInternal.tv_except, invalidLetters, invalidLetters._NP_RepositoryId, "invalidLetters", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_invalidLetters = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_invalidLetters)
omniORB.registerType(invalidLetters._NP_RepositoryId, _0_wordyGame._d_invalidLetters, _0_wordyGame._tc_invalidLetters)
del invalidLetters

# exception invalidCredentials
_0_wordyGame.invalidCredentials = omniORB.newEmptyClass()
class invalidCredentials (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyGame/invalidCredentials:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyGame.invalidCredentials = invalidCredentials
_0_wordyGame._d_invalidCredentials  = (omniORB.tcInternal.tv_except, invalidCredentials, invalidCredentials._NP_RepositoryId, "invalidCredentials", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_invalidCredentials = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_invalidCredentials)
omniORB.registerType(invalidCredentials._NP_RepositoryId, _0_wordyGame._d_invalidCredentials, _0_wordyGame._tc_invalidCredentials)
del invalidCredentials

# exception invalidUser
_0_wordyGame.invalidUser = omniORB.newEmptyClass()
class invalidUser (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyGame/invalidUser:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyGame.invalidUser = invalidUser
_0_wordyGame._d_invalidUser  = (omniORB.tcInternal.tv_except, invalidUser, invalidUser._NP_RepositoryId, "invalidUser", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_invalidUser = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_invalidUser)
omniORB.registerType(invalidUser._NP_RepositoryId, _0_wordyGame._d_invalidUser, _0_wordyGame._tc_invalidUser)
del invalidUser

# exception existingSession
_0_wordyGame.existingSession = omniORB.newEmptyClass()
class existingSession (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyGame/existingSession:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyGame.existingSession = existingSession
_0_wordyGame._d_existingSession  = (omniORB.tcInternal.tv_except, existingSession, existingSession._NP_RepositoryId, "existingSession", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_existingSession = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_existingSession)
omniORB.registerType(existingSession._NP_RepositoryId, _0_wordyGame._d_existingSession, _0_wordyGame._tc_existingSession)
del existingSession

# exception timeElapsed
_0_wordyGame.timeElapsed = omniORB.newEmptyClass()
class timeElapsed (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyGame/timeElapsed:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyGame.timeElapsed = timeElapsed
_0_wordyGame._d_timeElapsed  = (omniORB.tcInternal.tv_except, timeElapsed, timeElapsed._NP_RepositoryId, "timeElapsed", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_timeElapsed = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_timeElapsed)
omniORB.registerType(timeElapsed._NP_RepositoryId, _0_wordyGame._d_timeElapsed, _0_wordyGame._tc_timeElapsed)
del timeElapsed

# exception noWinner
_0_wordyGame.noWinner = omniORB.newEmptyClass()
class noWinner (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyGame/noWinner:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyGame.noWinner = noWinner
_0_wordyGame._d_noWinner  = (omniORB.tcInternal.tv_except, noWinner, noWinner._NP_RepositoryId, "noWinner", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_noWinner = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_noWinner)
omniORB.registerType(noWinner._NP_RepositoryId, _0_wordyGame._d_noWinner, _0_wordyGame._tc_noWinner)
del noWinner

# exception drawWinners
_0_wordyGame.drawWinners = omniORB.newEmptyClass()
class drawWinners (CORBA.UserException):
    _NP_RepositoryId = "IDL:wordyGame/drawWinners:1.0"

    def __init__(self, message):
        CORBA.UserException.__init__(self, message)
        self.message = message

_0_wordyGame.drawWinners = drawWinners
_0_wordyGame._d_drawWinners  = (omniORB.tcInternal.tv_except, drawWinners, drawWinners._NP_RepositoryId, "drawWinners", "message", (omniORB.tcInternal.tv_string,0))
_0_wordyGame._tc_drawWinners = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_drawWinners)
omniORB.registerType(drawWinners._NP_RepositoryId, _0_wordyGame._d_drawWinners, _0_wordyGame._tc_drawWinners)
del drawWinners

# interface WordyInt
_0_wordyGame._d_WordyInt = (omniORB.tcInternal.tv_objref, "IDL:wordyGame/WordyInt:1.0", "WordyInt")
omniORB.typeMapping["IDL:wordyGame/WordyInt:1.0"] = _0_wordyGame._d_WordyInt
_0_wordyGame.WordyInt = omniORB.newEmptyClass()
class WordyInt :
    _NP_RepositoryId = _0_wordyGame._d_WordyInt[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_wordyGame.WordyInt = WordyInt
_0_wordyGame._tc_WordyInt = omniORB.tcInternal.createTypeCode(_0_wordyGame._d_WordyInt)
omniORB.registerType(WordyInt._NP_RepositoryId, _0_wordyGame._d_WordyInt, _0_wordyGame._tc_WordyInt)

# WordyInt operations and attributes
WordyInt._d_verifyLogin = ((omniORB.typeMapping["IDL:wordyGame/Player:1.0"], ), (omniORB.tcInternal.tv_boolean, ), {_0_wordyGame.invalidCredentials._NP_RepositoryId: _0_wordyGame._d_invalidCredentials, _0_wordyGame.invalidUser._NP_RepositoryId: _0_wordyGame._d_invalidUser, _0_wordyGame.existingSession._NP_RepositoryId: _0_wordyGame._d_existingSession})
WordyInt._d_newGame = (((omniORB.tcInternal.tv_string,0), ), (), {_0_wordyGame.noOtherPlayersAvailable._NP_RepositoryId: _0_wordyGame._d_noOtherPlayersAvailable})
WordyInt._d_receiveLetters = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:wordyGame/CharSeq:1.0"], ), None)
WordyInt._d_submitWord = (((omniORB.tcInternal.tv_string,0), (omniORB.tcInternal.tv_string,0)), (), {_0_wordyGame.invalidWord._NP_RepositoryId: _0_wordyGame._d_invalidWord, _0_wordyGame.noSubmittedWord._NP_RepositoryId: _0_wordyGame._d_noSubmittedWord, _0_wordyGame.invalidLetters._NP_RepositoryId: _0_wordyGame._d_invalidLetters})
WordyInt._d_getGameTime = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_long, ), None)
WordyInt._d_startGameTime = ((omniORB.tcInternal.tv_long, (omniORB.tcInternal.tv_string,0)), (), None)
WordyInt._d_getGameState = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
WordyInt._d_getWinState = (((omniORB.tcInternal.tv_string,0), ), (omniORB.tcInternal.tv_boolean, ), None)
WordyInt._d_getRoundWin = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), {_0_wordyGame.noWinner._NP_RepositoryId: _0_wordyGame._d_noWinner, _0_wordyGame.drawWinners._NP_RepositoryId: _0_wordyGame._d_drawWinners})
WordyInt._d_signalRoundEnd = (((omniORB.tcInternal.tv_string,0), ), (), None)
WordyInt._d_getGameWin = (((omniORB.tcInternal.tv_string,0), ), ((omniORB.tcInternal.tv_string,0), ), None)
WordyInt._d_logout = (((omniORB.tcInternal.tv_string,0), ), (), None)
WordyInt._d_topPlayers = ((), (omniORB.typeMapping["IDL:wordyGame/StringSeq:1.0"], ), None)
WordyInt._d_topWords = ((), (omniORB.typeMapping["IDL:wordyGame/WordSeq:1.0"], ), None)

# WordyInt object reference
class _objref_WordyInt (CORBA.Object):
    _NP_RepositoryId = WordyInt._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def verifyLogin(self, *args):
        return self._obj.invoke("verifyLogin", _0_wordyGame.WordyInt._d_verifyLogin, args)

    def newGame(self, *args):
        return self._obj.invoke("newGame", _0_wordyGame.WordyInt._d_newGame, args)

    def receiveLetters(self, *args):
        return self._obj.invoke("receiveLetters", _0_wordyGame.WordyInt._d_receiveLetters, args)

    def submitWord(self, *args):
        return self._obj.invoke("submitWord", _0_wordyGame.WordyInt._d_submitWord, args)

    def getGameTime(self, *args):
        return self._obj.invoke("getGameTime", _0_wordyGame.WordyInt._d_getGameTime, args)

    def startGameTime(self, *args):
        return self._obj.invoke("startGameTime", _0_wordyGame.WordyInt._d_startGameTime, args)

    def getGameState(self, *args):
        return self._obj.invoke("getGameState", _0_wordyGame.WordyInt._d_getGameState, args)

    def getWinState(self, *args):
        return self._obj.invoke("getWinState", _0_wordyGame.WordyInt._d_getWinState, args)

    def getRoundWin(self, *args):
        return self._obj.invoke("getRoundWin", _0_wordyGame.WordyInt._d_getRoundWin, args)

    def signalRoundEnd(self, *args):
        return self._obj.invoke("signalRoundEnd", _0_wordyGame.WordyInt._d_signalRoundEnd, args)

    def getGameWin(self, *args):
        return self._obj.invoke("getGameWin", _0_wordyGame.WordyInt._d_getGameWin, args)

    def logout(self, *args):
        return self._obj.invoke("logout", _0_wordyGame.WordyInt._d_logout, args)

    def topPlayers(self, *args):
        return self._obj.invoke("topPlayers", _0_wordyGame.WordyInt._d_topPlayers, args)

    def topWords(self, *args):
        return self._obj.invoke("topWords", _0_wordyGame.WordyInt._d_topWords, args)

omniORB.registerObjref(WordyInt._NP_RepositoryId, _objref_WordyInt)
_0_wordyGame._objref_WordyInt = _objref_WordyInt
del WordyInt, _objref_WordyInt

# WordyInt skeleton
__name__ = "wordyGame__POA"
class WordyInt (PortableServer.Servant):
    _NP_RepositoryId = _0_wordyGame.WordyInt._NP_RepositoryId


    _omni_op_d = {"verifyLogin": _0_wordyGame.WordyInt._d_verifyLogin, "newGame": _0_wordyGame.WordyInt._d_newGame, "receiveLetters": _0_wordyGame.WordyInt._d_receiveLetters, "submitWord": _0_wordyGame.WordyInt._d_submitWord, "getGameTime": _0_wordyGame.WordyInt._d_getGameTime, "startGameTime": _0_wordyGame.WordyInt._d_startGameTime, "getGameState": _0_wordyGame.WordyInt._d_getGameState, "getWinState": _0_wordyGame.WordyInt._d_getWinState, "getRoundWin": _0_wordyGame.WordyInt._d_getRoundWin, "signalRoundEnd": _0_wordyGame.WordyInt._d_signalRoundEnd, "getGameWin": _0_wordyGame.WordyInt._d_getGameWin, "logout": _0_wordyGame.WordyInt._d_logout, "topPlayers": _0_wordyGame.WordyInt._d_topPlayers, "topWords": _0_wordyGame.WordyInt._d_topWords}

WordyInt._omni_skeleton = WordyInt
_0_wordyGame__POA.WordyInt = WordyInt
omniORB.registerSkeleton(WordyInt._NP_RepositoryId, WordyInt)
del WordyInt
__name__ = "wordyGame"

#
# End of module "wordyGame"
#
__name__ = "Wordy_idl"

_exported_modules = ( "wordyGame", )

# The end.
