package wordyGame;

/**
* wordyGame/drawWinnersHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class drawWinnersHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.drawWinners value = null;

  public drawWinnersHolder ()
  {
  }

  public drawWinnersHolder (wordyGame.drawWinners initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.drawWinnersHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.drawWinnersHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.drawWinnersHelper.type ();
  }

}
