package wordyGame;


/**
* wordyGame/drawWinners.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class drawWinners extends org.omg.CORBA.UserException
{
  public String message = null;

  public drawWinners ()
  {
    super(drawWinnersHelper.id());
  } // ctor

  public drawWinners (String _message)
  {
    super(drawWinnersHelper.id());
    message = _message;
  } // ctor


  public drawWinners (String $reason, String _message)
  {
    super(drawWinnersHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class drawWinners
