package wordyGame;


/**
* wordyGame/existingSession.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class existingSession extends org.omg.CORBA.UserException
{
  public String message = null;

  public existingSession ()
  {
    super(existingSessionHelper.id());
  } // ctor

  public existingSession (String _message)
  {
    super(existingSessionHelper.id());
    message = _message;
  } // ctor


  public existingSession (String $reason, String _message)
  {
    super(existingSessionHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class existingSession
