package wordyGame;

/**
* wordyGame/existingSessionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class existingSessionHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.existingSession value = null;

  public existingSessionHolder ()
  {
  }

  public existingSessionHolder (wordyGame.existingSession initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.existingSessionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.existingSessionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.existingSessionHelper.type ();
  }

}
