package wordyGame;

/**
* wordyGame/invalidUserHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class invalidUserHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.invalidUser value = null;

  public invalidUserHolder ()
  {
  }

  public invalidUserHolder (wordyGame.invalidUser initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.invalidUserHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.invalidUserHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.invalidUserHelper.type ();
  }

}
