package wordyGame;


/**
* wordyGame/invalidWord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class invalidWord extends org.omg.CORBA.UserException
{
  public String message = null;

  public invalidWord ()
  {
    super(invalidWordHelper.id());
  } // ctor

  public invalidWord (String _message)
  {
    super(invalidWordHelper.id());
    message = _message;
  } // ctor


  public invalidWord (String $reason, String _message)
  {
    super(invalidWordHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class invalidWord
