package wordyGame;

/**
* wordyGame/invalidWordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class invalidWordHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.invalidWord value = null;

  public invalidWordHolder ()
  {
  }

  public invalidWordHolder (wordyGame.invalidWord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.invalidWordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.invalidWordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.invalidWordHelper.type ();
  }

}
