package wordyGame;


/**
* wordyGame/invalidLetters.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class invalidLetters extends org.omg.CORBA.UserException
{
  public String message = null;

  public invalidLetters ()
  {
    super(invalidLettersHelper.id());
  } // ctor

  public invalidLetters (String _message)
  {
    super(invalidLettersHelper.id());
    message = _message;
  } // ctor


  public invalidLetters (String $reason, String _message)
  {
    super(invalidLettersHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class invalidLetters
