package wordyGame;


/**
* wordyGame/invalidUser.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class invalidUser extends org.omg.CORBA.UserException
{
  public String message = null;

  public invalidUser ()
  {
    super(invalidUserHelper.id());
  } // ctor

  public invalidUser (String _message)
  {
    super(invalidUserHelper.id());
    message = _message;
  } // ctor


  public invalidUser (String $reason, String _message)
  {
    super(invalidUserHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class invalidUser
