package wordyGame;


/**
* wordyGame/invalidCredentials.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class invalidCredentials extends org.omg.CORBA.UserException
{
  public String message = null;

  public invalidCredentials ()
  {
    super(invalidCredentialsHelper.id());
  } // ctor

  public invalidCredentials (String _message)
  {
    super(invalidCredentialsHelper.id());
    message = _message;
  } // ctor


  public invalidCredentials (String $reason, String _message)
  {
    super(invalidCredentialsHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class invalidCredentials
