package wordyGame;

/**
* wordyGame/invalidCredentialsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class invalidCredentialsHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.invalidCredentials value = null;

  public invalidCredentialsHolder ()
  {
  }

  public invalidCredentialsHolder (wordyGame.invalidCredentials initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.invalidCredentialsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.invalidCredentialsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.invalidCredentialsHelper.type ();
  }

}
