package wordyGame;

/**
* wordyGame/noOtherPlayersAvailableHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class noOtherPlayersAvailableHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.noOtherPlayersAvailable value = null;

  public noOtherPlayersAvailableHolder ()
  {
  }

  public noOtherPlayersAvailableHolder (wordyGame.noOtherPlayersAvailable initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.noOtherPlayersAvailableHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.noOtherPlayersAvailableHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.noOtherPlayersAvailableHelper.type ();
  }

}
