package wordyGame;

/**
* wordyGame/noSubmittedWordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class noSubmittedWordHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.noSubmittedWord value = null;

  public noSubmittedWordHolder ()
  {
  }

  public noSubmittedWordHolder (wordyGame.noSubmittedWord initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.noSubmittedWordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.noSubmittedWordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.noSubmittedWordHelper.type ();
  }

}
