package wordyGame;


/**
* wordyGame/noSubmittedWord.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class noSubmittedWord extends org.omg.CORBA.UserException
{
  public String message = null;

  public noSubmittedWord ()
  {
    super(noSubmittedWordHelper.id());
  } // ctor

  public noSubmittedWord (String _message)
  {
    super(noSubmittedWordHelper.id());
    message = _message;
  } // ctor


  public noSubmittedWord (String $reason, String _message)
  {
    super(noSubmittedWordHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class noSubmittedWord
