package wordyGame;


/**
* wordyGame/noWinner.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class noWinner extends org.omg.CORBA.UserException
{
  public String message = null;

  public noWinner ()
  {
    super(noWinnerHelper.id());
  } // ctor

  public noWinner (String _message)
  {
    super(noWinnerHelper.id());
    message = _message;
  } // ctor


  public noWinner (String $reason, String _message)
  {
    super(noWinnerHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class noWinner
