package wordyGame;

/**
* wordyGame/PlayerHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class PlayerHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.Player value = null;

  public PlayerHolder ()
  {
  }

  public PlayerHolder (wordyGame.Player initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.PlayerHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.PlayerHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.PlayerHelper.type ();
  }

}
