package wordyGame;


/**
* wordyGame/Player.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class Player implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public String password = null;

  public Player ()
  {
  } // ctor

  public Player (String _username, String _password)
  {
    username = _username;
    password = _password;
  } // ctor

} // class Player
