package wordyGame;

/**
* wordyGame/timeElapsedHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class timeElapsedHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.timeElapsed value = null;

  public timeElapsedHolder ()
  {
  }

  public timeElapsedHolder (wordyGame.timeElapsed initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.timeElapsedHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.timeElapsedHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.timeElapsedHelper.type ();
  }

}
