package wordyGame;


/**
* wordyGame/timeElapsed.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class timeElapsed extends org.omg.CORBA.UserException
{
  public String message = null;

  public timeElapsed ()
  {
    super(timeElapsedHelper.id());
  } // ctor

  public timeElapsed (String _message)
  {
    super(timeElapsedHelper.id());
    message = _message;
  } // ctor


  public timeElapsed (String $reason, String _message)
  {
    super(timeElapsedHelper.id() + "  " + $reason);
    message = _message;
  } // ctor

} // class timeElapsed
