package wordyGame;


/**
* wordyGame/Word.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class Word implements org.omg.CORBA.portable.IDLEntity
{
  public String username = null;
  public String wordSub = null;

  public Word ()
  {
  } // ctor

  public Word (String _username, String _wordSub)
  {
    username = _username;
    wordSub = _wordSub;
  } // ctor

} // class Word
