package wordyGame;

/**
* wordyGame/WordyIntHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class WordyIntHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.WordyInt value = null;

  public WordyIntHolder ()
  {
  }

  public WordyIntHolder (wordyGame.WordyInt initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.WordyIntHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.WordyIntHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.WordyIntHelper.type ();
  }

}
