package wordyGame;

/**
* wordyGame/WordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public final class WordHolder implements org.omg.CORBA.portable.Streamable
{
  public wordyGame.Word value = null;

  public WordHolder ()
  {
  }

  public WordHolder (wordyGame.Word initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = wordyGame.WordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    wordyGame.WordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return wordyGame.WordHelper.type ();
  }

}
