package wordyGame;


/**
* wordyGame/WordyIntOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

public interface WordyIntOperations 
{

  //checks user login
  boolean verifyLogin (wordyGame.Player p) throws wordyGame.invalidCredentials, wordyGame.invalidUser, wordyGame.existingSession;

  //starts a new game at player's initiate
  void newGame (String username) throws wordyGame.noOtherPlayersAvailable;

  //gets letter array from server
  char[] receiveLetters (String username);

  //validates a submitted word
  void submitWord (String word, String username) throws wordyGame.invalidWord, wordyGame.noSubmittedWord, wordyGame.invalidLetters;

  //gets game timer
  int getGameTime (String username);

  //start timer
  void startGameTime (int seconds, String username);

  //checks if a game is ongoing
  boolean getGameState (String username);

  //checks the winners of a game
  boolean getWinState (String username);

  //gets winner for the current round
  String getRoundWin (String username) throws wordyGame.noWinner, wordyGame.drawWinners;
  void signalRoundEnd (String username);

  //gets winner for game
  String getGameWin (String username);
  void logout (String username);

  //returns a list of top 5 players
  String[] topPlayers ();

  //returns a list of top 5 submitted word
  wordyGame.Word[] topWords ();
} // interface WordyIntOperations
