package wordyGame;


/**
* wordyGame/WordyIntHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Wordy.idl
* Sunday, June 18, 2023 11:16:05 PM SGT
*/

abstract public class WordyIntHelper
{
  private static String  _id = "IDL:wordyGame/WordyInt:1.0";

  public static void insert (org.omg.CORBA.Any a, wordyGame.WordyInt that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static wordyGame.WordyInt extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (wordyGame.WordyIntHelper.id (), "WordyInt");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static wordyGame.WordyInt read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_WordyIntStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, wordyGame.WordyInt value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static wordyGame.WordyInt narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof wordyGame.WordyInt)
      return (wordyGame.WordyInt)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      wordyGame._WordyIntStub stub = new wordyGame._WordyIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static wordyGame.WordyInt unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof wordyGame.WordyInt)
      return (wordyGame.WordyInt)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      wordyGame._WordyIntStub stub = new wordyGame._WordyIntStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
